### ISSUE TITLE
CSS for the start branch is a bit off

### ISSUE THREAD

**Issue by S-Ethan** [planetoftheweb/angulardata#2]
Hey Ray,

I'm taking your second angular course, and am following along well so far,
but when I got to ch02_02, I noticed the nav bar's CSS was clearly off. 
so I looked at the CSS file found the "branding" class, and saw that the padding was this:
`padding: 10px, 15px, 10px, 60px;`
I changed the `60px` to `15px` and that seemed to fix it.

Curious, I looked at the CSS file for the ch02_02 branch. 
It was a lot different in concerns to the "start" branch's CSS file.
This file didn't even have a `padding` element.
Copying the code, I replaced it with the existing code I had when I cloned the start branch.
Looking further, I saw that all of the branches's CSS files were good EXCEPT the start branch's.

Looks like it's a very simple fix. Keep up the great work on lynda.com. Look forward to more angular courses.

**Comment by planetoftheweb** [comment]
Hey Ethan,

Thanks for letting me know. This course was weird because I was trying to keep some of the original movies while updating the rest. Also Firebase updated to a new version like a week after it was released, so I have to do another update. I'm on a couple of other projects right now, so it will be a while before I can take care of that. I'll take a look at this as well.

About the start branch.
